spring:
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  jpa:
    generate-ddl: false
#    generate-ddl: true
    hibernate:
      ddl-auto: none
#      ddl-auto: create-drop

#    show-sql: true

logging:
  level:
    ROOT: ERROR