server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mainDB
cross-origin: http://localhost:5173
mongock:
  runner-type: "ApplicationRunner"
  change-logs-scan-package:
    - ru.otus.hw.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    ROOT: ERROR
