spring:
  main:
    banner-mode: console
  messages:
    baseName: messages
    encoding: UTF-8
    # Не дает свалиться в системную локаль если не найден файл для переданной в MessageSource
    # Если false то будут браться сообщения из дефолтного файла, если true, то из файла соответствующего системной локали
    fallbackToSystemLocale: false
  profiles:
    active:
      rus_test
---
spring:
  config:
    activate:
      on-profile: engl_test
test:
  rightAnswersCountToPass: 2
  locale: en
  fileNameByLocaleTag:
    ru-RU: questions_ru.csv
    en: questions.csv
---
spring:
  config:
    activate:
      on-profile: rus_test
test:
  rightAnswersCountToPass: 3
  locale: ru_RU
  fileNameByLocaleTag:
    ru-RU: questions_ru.csv
    en: questions.csv
